### PR TITLE
Fixes 18500

### PR DESCRIPTION
**Pull request by rhapsodyv**
### Description

Fix some typos, some warnings (redefinition), font load, etc

### CODE REVIEW

**Comment by MKS-Sean** [comment]
OK, I'll fix it. On the question of the font, I will continue to test it

**Comment by rhapsodyv** [comment]
> OK, I'll fix it. On the question of the font, I will continue to test it

The font issue is random because the way the file is saved to SD. Some is saved with long file name fat flag, others dont. It explain why works for mks, but dont work for Keith. The fix I did, may solve it to everyone (I think).

**Comment by MKS-Sean** [comment]
The nano motherboard has bootloader to update the image and font files.Other boards can only update the image and font library according to the firmware update function. Maybe you'll have the problem you're talking about

**Comment by rhapsodyv** [comment]
> The nano motherboard has bootloader to update the image and font files.Other boards can only update the image and font library according to the firmware update function. Maybe you'll have the problem you're talking about

The problem seems related because some files in SD don't have a "long name flag". Yours have. Keith don't have. This flag is put by the operation system, we had no control.

What I did is the same I did for the icon load: make the code works even if the file saved in SD isn't with that flag.

**Comment by thisiskeithb** [comment]
@makerbase-mks / @MKS-Sean: Can you merge this PR?

**Comment by makerbase-mks** [comment]
@thisiskeithb Ok, what other changes do I need to make?

**Pull request merged**
